### ISSUE TITLE
linearRegression

### ISSUE THREAD

**Issue by andreavitaletti** [DeanCording/node-red-contrib-statistics#1]
Hi 

I have the simple flow at the end of this post

There is a function generating pairs of data as in the following

```
var count = context.get('count') || 0;
count += 1;
context.set('count',count);
msg.payload=[count,10*count];
msg.topic="data";
return msg; 
```

when I call data/linearRegression I always get 

data/linearRegression : msg.payload : Object
{ m: null, b: null }

Apparently the problem is on how data are stored indeed if I call 

data/sample I get an array instead of an array of arrays (see below)

data/sample : msg.payload : array[120]
[ 86, 38, 101, 37, 95, 50, 53, 32, 35, 102 … ]

Any advice?

Bests, Andrea

[{"id":"5ca8b1d1.323d4","type":"tab","label":"Flow 5"},{"id":"24ed96e7.bc923a","type":"statistics","z":"5ca8b1d1.323d4","name":"","stripFunction":false,"x":477.3808898925781,"y":344.04758453369135,"wires":[["bb08a2b8.04585"]]},{"id":"f492f97e.debd38","type":"inject","z":"5ca8b1d1.323d4","name":"","topic":"","payload":"","payloadType":"date","repeat":"1","crontab":"","once":false,"x":134.0475591023764,"y":145.23810386657715,"wires":[["23fa8b06.fcb804"]]},{"id":"bb08a2b8.04585","type":"debug","z":"5ca8b1d1.323d4","name":"","active":true,"console":"false","complete":"false","x":732.3808898925781,"y":348.5714085896809,"wires":[]},{"id":"23fa8b06.fcb804","type":"function","z":"5ca8b1d1.323d4","name":"","func":"var count = context.get('count') || 0;\ncount += 1;\ncontext.set('count',count);\n\nmsg.payload=[count,10*count];\nmsg.topic=\"data\";\n\n\nreturn msg;","outputs":1,"noerr":0,"x":305.71420033772796,"y":144.99998474121094,"wires":[["24ed96e7.bc923a","9435bd67.6aa4f"]]},{"id":"7804e6ae.4402b8","type":"inject","z":"5ca8b1d1.323d4","name":"LR","topic":"linearRegression","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":169.64275360107422,"y":382.8571472167969,"wires":[["24ed96e7.bc923a"]]},{"id":"9435bd67.6aa4f","type":"debug","z":"5ca8b1d1.323d4","name":"","active":true,"console":"false","complete":"false","x":593.452402750651,"y":158.80952199300128,"wires":[]},{"id":"4efece3f.fef02","type":"inject","z":"5ca8b1d1.323d4","name":"size","topic":"data/size","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":174.04757690429688,"y":575.7142333984375,"wires":[["24ed96e7.bc923a"]]},{"id":"2d406ab8.0ee176","type":"inject","z":"5ca8b1d1.323d4","name":"sample","topic":"data/sample","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":174.04757690429688,"y":435.7142333984375,"wires":[["24ed96e7.bc923a"]]},{"id":"6f12aae9.010dc4","type":"inject","z":"5ca8b1d1.323d4","name":"clear","topic":"data/clear","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":190.71424865722656,"y":504.0475769042969,"wires":[["24ed96e7.bc923a"]]}]

**Comment by brylie** [comment]
I am having trouble importing your flow. What version of Node-Red are you running?

**Comment by andreavitaletti** [comment]
0.16.2

anyway the flow is very easy ... and the function is the one in the previous post

![flow](https://cloud.githubusercontent.com/assets/3737862/25227073/8a5d9b42-25c7-11e7-9021-92cdb4c929d7.png)

**Comment by brylie** [comment]
Hm, I can't even get the plugin to work with a simple flow:

![screenshot_20170420_151101](https://cloud.githubusercontent.com/assets/17307/25230143/9a2ff894-25db-11e7-86ed-8a785c71fc65.png)

**Comment by andreavitaletti** [comment]
In my case min and max works, I basically followed the instruction on the readme

I have a function triggered every 1s by an inject node with the following code

```
msg.payload=10*Math.random()
msg.topic="data"
return msg;
```
the output of this node goes in input to the statistic node and then eventually I generate a message to the statistic node with input /data/max

It works.

Notice that if I import the simple statistics lib as described [here](http://stackoverflow.com/questions/38481130/use-an-external-js-library-in-a-node-red-function) and use the following code all works 

```
var ST = context.global.get('st');
//msg.payload = ST.linearRegression([[0, 0], [1, 1]]); // => { m: 1, b: 0 }

var vec = msg.payload.split("\n");
//var vec = ["[0, 1]", "[1, 2]", "[2, 4]"]

var data = [];
for (var i = 0; i < vec.length-1; i++) {
    var array_elem = JSON.parse(vec[i]);
    data.push(array_elem);
}

console.log(data);

msg.payload=ST.linearRegression(data);
return msg;
```

**Comment by DeanCording** [comment]
Hmm, looking at the code I'm not sure how I ever intended this to work.

Firstly, the statistics node should only be fed numbers.  It tries its best to extract a number from what it receives.  When you fed in an array of numbers, it just extracts the first element that is a number and discards the rest.

Secondly, linearRegression requires an array of points, which the node just doesn't record so it isn't surprising that it returns nulls.

**Comment by andreavitaletti** [comment]
ok I see ... thank you

**Comment by DeanCording** [comment]
Sorry about that.  The solution you posted of importing the simple statistics lib and using it in your own function is probably the best.

**Comment by DeanCording** [comment]
Remove non-functioning linearRegression method.
