### ISSUE TITLE
[Request] dataset limit + insert full dataset

### ISSUE THREAD

**Issue by Sh0ku** [DeanCording/node-red-contrib-statistics#4]
Hello,
I'm new to GitHub so I hope this is the right place for this request.
I would like to set a maximum array size and only hold the latest xxx values. 
Currently I have to hold the array values in an extra function node and resend all values each time I get a new one.

Is there a possibility to insert an array of values at once and output the saved array of values. ?

Eventually i'll try to add that functionality on my own and publish it here, but im not that good with coding it right now.

Thanks in advance for reading this and again I hope it's the right place for this.
ManniMo

**Comment by DeanCording** [comment]
Welcome,

Yes you have come to the right place.

> I would like to set a maximum array size and only hold the latest xxx values.

That's a great idea!  It should be easy to implement, just give me a day or two.

> Is there a possibility to insert an array of values at once and output the saved array of values. ?

Actually, that could be useful to save data at shutdown and restore it at startup.  It should also be easy to do.  Let me have a look and let you know.

One of the best ways to learn coding is to look at what other people have done.  Have a look inside my code to see how it works and feel free to ask any questions.

Thanks,

Dean

**Comment by DeanCording** [comment]
All of these features have been implemented and a new version released.

Enjoy!
