### ISSUE TITLE
Unclear documentation of topic format

### ISSUE THREAD

**Issue by andersea** [DeanCording/node-red-contrib-statistics#6]
The documentation says that:

"When a message with a topic that **ends** in a statistical function name is received"

So from this I assume that I can make a topic like this: "myData_mean", and statistics will know that i want the mean, since the topic _ends_ with "mean".

But the way it is coded, the topic splitter is required to be "/". This is rather confusing.

**Comment by DeanCording** [comment]
Thanks for reporting this.  Like all nodes in Node Red, it uses the MQTT topic format that specifies the '/' as a topic level separator.  I've clarified the documentation.
