### ISSUE TITLE
Add support for linearRegression?

### ISSUE THREAD

**Issue by andersea** [DeanCording/node-red-contrib-statistics#8]
Is this possible? Would be nice, etc.

Thanks.

**Comment by DeanCording** [comment]
Yes, it should be possible.  There is a new release of Simple Statistics out so I will be

**Comment by DeanCording** [comment]
Let me have a look.  There is a new release of Simple Statistics with some more functions which I am going to incorporate shortly.

**Comment by DeanCording** [comment]
Actually, the reason I left it out was that it requires data items to be two-element of arrays which made it difficult to handle in a generic statistics node - how does it know you want a linear regression?  How does it handle a mix of single and double data items?  What if you ask for the mean of a set of data points?

One possibility is to have a separate linear regression node.   What use case did you have in mind?

**Comment by andersea** [comment]
I made my own node for linearRegression a while back, since it wasn't supported by this project.

Here is my implementation:

https://github.com/andersea/nrc-ss/blob/master/src/regression.ts

As you can see it is as simple as possible. It never stores any data, the array is simply fed to the library as is, and the result is returned.

If I may be so bold as to venture an opinion. I think keeping track of data inside the node is not a good idea. I don't see what the need is. For me I would prefer that all the library function where available like in my implementation, with no local state. Having to clear the node when you want to analyze a new set of data, is just extra work that I don't need.

I don't really understand what you mean by the question "how does it know you want a linear regression?". It just reads it from the topic, like with all the other functions? I don't see why you need special handling of the linearRegression function. It is just an array of 'stuff'. I don't understand why it matters that it is an array of arrays or an array of numbers or anything else.

**Comment by DeanCording** [comment]
> I think keeping track of data inside the node is not a good idea. I don't see what the need is.

Whilst it is preferable that nodes don't contain state information, somewhere along the flow a node has to accumulate state when the flow is working with historical data. Most data generating nodes such as thermometers and meters,  just output the their current value.  If I want the mean for the last 15 minutes then I need to accumulate those data items somewhere and in the statistics node is just as good as anywhere.

>  Having to clear the node when you want to analyze a new set of data, is just extra work that I don't need.

You can clear and load new data in the same message.  Just add the 'clear' function to the topic and the node will clear the current data set before loading any data contained in the message.

> I don't really understand what you mean by the question "how does it know you want a linear regression?". It just reads it from the topic, like with all the other functions?

No, it is not an array of 'stuff', it is an array of either single data items or  XY data points. The node allows you to send it an array of data items. The problem would be determining if the data array contains two data items or a single data point.  linearRegression only works with an array of data points.  How would it handle a mix of data items and data points?

**Comment by andersea** [comment]
> If I want the mean for the last 15 minutes then I need to accumulate those data items somewhere and in the statistics node is just as good as anywhere.

Well I would prefer to do it in a dedicated node where I have the necessary control over time slicing and number of data points, but I can see how it might be a subjective viewpoint.

> The problem would be determining if the data array contains two data items or a single data point.

That would be an exceptional case for the kind of workflows I am usually working with. My streams would normally be uniformly shaped. I have a few workflows that mix different shapes of messages. These almost always end up in a join node where I do Key/Value topic join into a new single object. After that point the stream is uniformly shaped again as all objects have the same keys.

**Comment by DeanCording** [comment]
> I have the necessary control over time slicing and number of data points
The statistics node allows you to do that - you can either configure a fixed sized data buffer in the node, trigger a periodic flush of the buffer, or maintain your own buffer externally which you feed in as needed.

> That would be an exceptional case for the kind of workflows I am usually working with.
As a node developer, I have to anticipate all cases.

**Comment by andersea** [comment]
Fair enough. Closing.
