### ISSUE TITLE
Only act on dataset passed in

### ISSUE THREAD

**Issue by borpin** [DeanCording/node-red-contrib-statistics#9]
Am I right in thinking that the dataset is always cumulative until an explicit 'clear' is sent?

I want to only do a calculation on the dataset passed in.

Might I suggest an option that always clears the stored (or does not store it) dataset?

**Comment by DeanCording** [comment]
Yes, that is correct - data is accumulated into the dataset until an explicit clear is sent.

Note that you can have a data set in a clear message - this clears the existing data set and loads the one in the message.  If you then have a change node to remove the data set and change the topic to the statistics function, you can loop the message back through the statistics node using a switch node.

**Comment by borpin** [comment]
Ok, thanks.  I do think a Boolean option to always clear previous data set would be useful and more elegant than the additional steps above.

Cheers :smile:
